rule df_scripts_all:
    input:
        "data/processed/data_frames/eda_df.parquet",
        "data/processed/data_frames/fisher_exact/monthly_us_fisher_values.parquet",
        "data/processed/data_frames/fisher_exact/monthly_world_fisher_values.parquet",
        "data/processed/data_frames/authorid_date_sentiment_tweetcounts.parquet",
        "data/processed/data_frames/authorid_date_sentiment_tweetcounts_us.parquet",
        "data/processed/data_frames/authorid_state_sentiment_tweetcounts_us.parquet",
        "data/processed/data_frames/date_based_covid_data_ATV_and_unemployment.parquet",
        "data/processed/data_frames/correlation_df_VaccinationPercentage_ATV.parquet"

rule eda_of_fetched_data:
    input:
        "data/logs/insert_missed_tweets.txt"
    output:
        "data/processed/data_frames/eda_df.parquet"
    script:
        "src/df_scripts/eda_of_fetched_data.py"

rule combining_sentiment_predictions:
    input:
        "data/logs/tweet_sentiment_prediction.txt"
    output:
        "data/processed/tweet_sentiment_predictions/world_data_sentiments_raw.parquet",
        "data/processed/tweet_sentiment_predictions/us_data_sentiments_raw.parquet"
    script:
        "src/df_scripts/combining_sentiment_predictions.py"

rule id_date_filteredlabel:
    input:
        "data/processed/tweet_sentiment_predictions/world_data_sentiments_raw.parquet",
        "data/processed/tweet_sentiment_predictions/us_data_sentiments_raw.parquet"
    output:
        "data/processed/data_frames/us_id_date_state_filteredlabels.parquet"
        "data/processed/data_frames/world_id_date_filteredlabels.parquet",
        "data/processed/data_frames/world_anti_ids.parquet"
    script:
        "src/df_scripts/id_date_filteredlabel.py"

rule fisher_exact:
    input:
        "data/processed/data_frames/us_id_date_state_filteredlabels.parquet",
        "data/processed/data_frames/world_id_date_filteredlabels.parquet"
    output:
        "data/processed/data_frames/fisher_exact/monthly_us_fisher_values.parquet",
        "data/processed/data_frames/fisher_exact/monthly_world_fisher_values.parquet",
        "data/processed/data_frames/fisher_exact/daily_us_fisher_values.parquet",
        "data/processed/data_frames/fisher_exact/state_us_fisher_values.parquet"
    script:
        "src/df_scripts/fisher_exact.py"

rule authorid_date_sentiment_tweetcount:
    input:
        "data/processed/data_frames/world_id_date_filteredlabels.parquet",
        "data/processed/data_frames/us_id_date_state_filteredlabels.parquet"
    output:
        "data/processed/data_frames/authorid_date_sentiment_tweetcounts.parquet",
        "data/processed/data_frames/authorid_date_sentiment_tweetcounts_us.parquet",
        "data/processed/data_frames/authorid_state_sentiment_tweetcounts_us.parquet"
    script:
        "src/df_scripts/authorid_date_sentiment_tweetcount.py"

rule date_based_covid_data_ATV:
    input:
        "data/processed/data_frames/daily_us_fisher_values.parquet",
        "data/raw/covid_data/owid-covid-data.csv",
        "data/raw/socio_economic_params/date_base_unemployment.parquet"
    output:
        "data/processed/data_frames/date_based_covid_data_ATV_and_unemployment.parquet"
    script:
        "src/df_scripts/date_based_covid_data_and_atv.py"

rule state_based_vaccination_percentage_ATV:
    input:
        "data/raw/covid_data/us_state_vaccinations.parquet",
        "data/processed/data_frames/fisher_exact/state_us_fisher_values.parquet"
    output:
        "data/processed/data_frames/correlation_df_VaccinationPercentage_ATV.parquet"
    script:
        "src/df_scripts/state_based_vaccination_percentage_and_atv.py"

rule ctm_margin_cleaning:
    input:
        "data/processed/CTM/probs/probs_8_200_0.2.parquet",
        "data/processed/data_frames/world_anti_ids.parquet"
    output:
        "data/processed/CTM/probs/cleaned_probs_8_200_0.2.parquet",
        "data/processed/data_frames/cleaned_world_anti_ids.parquet"
    script:
        "src/df_scripts/ctm_margin_cleaning.py"

rule ctm_date_topic_count:
    input:
        "data/processed/data_frames/cleaned_world_anti_ids.parquet",
        "data/processed/CTM/probs/cleaned_probs_8_200_0.2.parquet",
    output:
        "data/processed/data_frames/id_date_topic_8_200_0.2.parquet"
        "data/processed/data_frames/date_topic_count_8_200_0.2.parquet"
    script:
        "src/df_scripts/ctm_date_topic_count.py"

rule ctm_day_keyword_count:
    input:
        "data/processed/data_frames/cleaned_world_anti_ids.parquet",
        "data/processed/data_frames/id_date_topic_8_200_0.2.parquet",
        "data/processed/CTM/topics/topics_8_200_0.2.parquet",
    output:
        expand(
            "data/processed/CTM/topics/day_keyword_count_for_topics_8_200_0.2/topic{topic}.parquet",
            topic=list(range(8)))
    script:
        "src/df_scripts/ctm_day_keyword_count.py"

rule ctm_date_bigram_count:
    input:
        "data/processed/data_frames/cleaned_world_anti_ids.parquet",
        "data/processed/data_frames/id_date_topic_8_200_0.2.parquet",
    output:
        "data/processed/data_frames/date_and_bigram_collocations_df.parquet"
    script:
        "src/df_scripts/ctm_date_bigram_count.py"

rule data_preparation_for_zenodo:
    input:
        "data/processed/CTM/probs/cleaned_probs_8_200_0.2.parquet",
        "data/processed/data_frames/cleaned_world_anti_ids.parquet",
        "data/processed/data_frames/world_data_sentiments_raw.parquet",
    output:
        "data/processed/data_frames/zenodo/ctm_predictions.parquet",
        "data/processed/data_frames/zenodo/attitude_predictions.parquet"
    script:
        "src/df_scripts/data_preparation_for_zenodo.py"
