rule sentiment_analysis_all:
    input:
        "data/logs/tweet_sentiment_prediction.txt",
        "data/logs/bert_model_fine_tuning.txt"

rule bert_model_fine_tuning:
    input:
        "data/crowdbreaks_data/crowdbreaks_tweet_ids_and_labels.csv",
        "data/crowdbreaks_data/crowdbreaks_tweets.parquet"
    output:
        "data/logs/bert_model_fine_tuning.txt"
    script:
        "src/sentiment_analysis/bert_model_fine_tuning.py"

rule tweet_sentiment_predictions:
    input:
        "data/logs/bert_model_fine_tuning.txt",
        "data/logs/insert_missed_tweets.txt"
    output:
        "data/logs/tweet_sentiment_prediction.txt"
    script:
        "src/sentiment_analysis/tweet_sentiment_prediction.py"