rule figures_all:
    input:
        "figures/all_figures/tweet_user_geoloc_counts.tiff",
        "figures/all_figures/user_topic_analysis_on_ChordDiagram.pdf",
        

rule fetched_data_barplot:
    input:
        "figures/icons/twitter_bird_icon.png",
        "figures/icons/avatar_icon.png",
        "figures/icons/location_icon.png",
        "data/processed/dataframes/eda_df.parquet"
    output:
        "figures/all_figures/tweet_user_geoloc_counts.tiff"
    script:
        "src/figures/fetched_data_barplot.py"

rule chordplot:
    input:
        "data/processed/data_frames/prepared_links.csv"
    output:
        "figures/all_figures/user_topic_analysis_on_ChordDiagram.pdf"
    script:
        "src/figures/chordplot.R"

rule figures_of_socio_economic_parameters_and_atv:
    input:
        "main_configs.json",
        "data/processed/data_frames/combined_socio_economic_parameters.parquet"
    output:
        "figures/supp_figure_svgs/figure10{alphabet}.svg",
        "figures/main_figure_svgs/figure3C.svg",
        "figures/main_figure_svgs/figure3D.svg",
        "figures/supp_figure_svgs/figure11.svg",
        "figures/supp_figure_svgs/figure12.svg",
        "data/processed/data_frames/socio_economic_params_pca_coefficients.parquet"
    notebook:
        "src/figure_notebooks/figures_of_socio_economic_parameters_and_atv.ipynb"